### ISSUE TITLE
SetMaasCreds throws an error, is "lab" hardcoded?

### ISSUE THREAD

**Issue by oneilcin** [DStorck/gogo#10]
credentials:
  f46a8a99-4bec-11e8-b7ae-0abdb26a8ff8:
    cindy:
      auth-type: oauth1
      maas-oauth: REDACTED

Since Juju 2 is being run for the first time, downloading latest cloud information.
Fetching latest public cloud list...
Updated your list of public clouds with 5 cloud regions deleted:

    deleted cloud region:
        - aws/eu-west-3
        - google/europe-west2
        - google/europe-west3
        - google/southamerica-east1
        - google/us-east4
ERROR cloud lab not valid

2018/04/29 20:36:14 add-credential failed with exit status 1
exit status 1

**Comment by DStorck** [comment]
fixed by https://github.com/DStorck/gogo/commit/094031973c44d4dc98ec723226d2eb58c6c28cd0
