### ISSUE TITLE
New Method to check if juju controller exists, return bool

### ISSUE THREAD

**Issue by oneilcin** [DStorck/gogo#25]
Spinup blocks creating the juju controller.  I can have a thread wait for this, but then I would like to check if the juju controller exists.  We could have a case where it errors on creating the controller.
If it doesn't exist after returning from Spinup, I can create an error event.

All of the other commands (ClusterReady, DestroyCluster) depend on the controller existing.  It would be nice to have that method for them too, to check before trying the command.

Not sure, but can you use the Name field as input to check if the controller exists yet?

**Comment by DStorck** [comment]
fixed by https://github.com/DStorck/gogo/pull/29
